fix

diff --git a/tenant-config/templates/configmap.yaml b/tenant-config/templates/configmap.yaml
--- a/tenant-config/templates/configmap.yaml
+++ b/tenant-config/templates/configmap.yaml
@@ -225,3 +225,18 @@ data:
     echo "❌ Failed to set password. HTTP status: $PASS_RESPONSE"
       exit 1
     fi
+
+    TARGET_GROUP="${PROJ_UUID}_Host-Manager-Group"
+    GROUP_ID=$(curl -s -X GET "$KEYCLOAK_URL/admin/realms/master/groups" \
+    -H "Authorization: Bearer $IDP_AT" | jq -r ".[] | select(.name==\"$TARGET_GROUP\") | .id")
+
+    RESP=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
+    "$KEYCLOAK_URL/admin/realms/master/users/$USER_ID/groups/$GROUP_ID" \
+    -H "Authorization: Bearer $IDP_AT")
+
+    if [[ "$RESP" == "204" ]]; then
+      echo "✅ Successfully assigned '$TARGET_GROUP' to '$DEFAULT_USER'."
+    else
+      echo "❌ Failed to assign group. HTTP code: $RESP"
+      exit 1
+    fi
